# This is a default home.nix generated by the follwing hone-manager command
#
# home-manager init ./
{ config, lib, pkgs, ... }:

{
  # Home Manager needs a bit of information about you and the paths it should
  # manage.
  home.username = lib.mkDefault "pharo";
  home.homeDirectory = lib.mkDefault "/home/${config.home.username}";

  # This value determines the Home Manager release that your configuration is
  # compatible with. This helps avoid breakage when a new Home Manager release
  # introduces backwards incompatible changes.
  #
  # You should not change this value, even if you update Home Manager. If you do
  # want to update the value, then make sure to first check the Home Manager
  # release notes.
  home.stateVersion = "24.11"; # Please read the comment before changing.

  # The home.packages option allows you to install Nix packages into your
  # environment.
  # home.packages = with pkgs; [];

  # Configure user identity and preferences (user-level priority)
  custom.user = {
    name = lib.mkOverride 500 "Cole Glotfelty";
    email = lib.mkOverride 500 "git@postagepaid.cc";
  };

  custom.defaults = {
    terminal = lib.mkOverride 500 "kitty";
    browser = lib.mkOverride 500 "librewolf";
    editor = lib.mkOverride 500 "nvim";
    fileManager = lib.mkOverride 500 "ranger";
    copyCommand = lib.mkOverride 500 "wl-copy";
    mailClient = lib.mkOverride 500 "thunderbird";
  };

  home.sessionVariables = {
    EDITOR = config.custom.defaults.editor;
    TERMINAL = config.custom.defaults.terminal;
    NIX_PATH = "nixpkgs=channel:nixos-unstable";
    NIX_LOG = "info";
    PROJECT_DIRS = "$HOME ${config.custom.paths.projects} ${config.custom.paths.remote}/Halligan/cs21";
  };

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;
}
